Fix bugs

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -25,7 +25,7 @@ install-apt() {
 install_base() {
     sudo apt-get update || fail
     sudo apt-get upgrade -y || fail
-    sudo apt-get install wget curl -y || fail
+    sudo apt-get install wget curl apt-utils gnupg2 -y || fail
 
     install nodejs
     install python
@@ -92,7 +92,7 @@ install_desktop() {
         # printscreen keybind deps
         sudo apt-get install exiftool xclip -y || fail
         make_bindings || fail
-    ) | prepend 'keybinds'
+    ) | prepend 'keybinds' || fail
 
     # install zh & ja
     (
@@ -100,7 +100,7 @@ install_desktop() {
         sudo apt-get install ibus-anthy -y || fail
         sudo apt-get install ibus-clutter ibus-gtk ibus-gtk3 ibus-qt4 -y || fail
         ibus restart
-    ) | prepend 'lang'
+    ) | prepend 'lang' || fail
 
     echo "#### Removing unity-webapps-common ####"
     sudo apt-get remove unity-webapps-common -y
@@ -108,7 +108,7 @@ install_desktop() {
     echo "#### Setting favorite apps ####"
     dconf write "/org/gnome/shell/favorite-apps" "['firefox.desktop', 'nemo.desktop', 'org.gnome.Terminal.desktop', 'atom.desktop']"
 
-    echo 'PATH=$PATH:~/.local/bin:~/bin' >> ~/.bashrc
+    echo 'PATH=$PATH:~/.local/bin:~/bin' >> ~/.bashrc || fail
 
     echo "Patching nosplash"
     tee nosplash.patch<<EOL
@@ -154,10 +154,10 @@ EOL
 
     # Keepass config stuff
     # set global shortcut to ctrl+alt+a
-    
+
     # write default config file
     keepassxc & sleep 1 && pkill keepassxc
-    
+
     echo "Writing keepassxc config"
     tee ~/.config/keepassxc/keepassxc.ini<<EOL
 [General]
@@ -180,7 +180,7 @@ SSHAgent=false
 SingleInstance=true
 UseAtomicSaves=true
 UseGroupIconOnEntryCreation=true
- 
+
 [Browser]
 AlwaysAllowAccess=false
 AlwaysAllowUpdate=false
@@ -196,7 +196,7 @@ SupportKphFields=true
 UnlockDatabase=true
 UpdateBinaryPath=false
 UseCustomProxy=false
- 
+
 [GUI]
 DarkTrayIcon=false
 DetailSplitterState=@Invalid()
@@ -212,7 +212,7 @@ MinimizeToTray=false
 SearchViewState=@ByteArray()
 ShowTrayIcon=false
 SplitterState=@Invalid()
- 
+
 [Http]
 AlwaysAllowAccess=false
 AlwaysAllowUpdate=false
@@ -233,7 +233,7 @@ generator\LowerCase=true
 generator\Numbers=true
 generator\SpecialChars=false
 generator\UpperCase=true
- 
+
 [security]
 IconDownloadFallbackToGoogle=false
 autotypeask=true
@@ -409,7 +409,7 @@ install_nodejs() {
     [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
 
     nvm install node || fail
-    
+
     # install yarn
     curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
@@ -602,7 +602,7 @@ install_python() {
 
     # ml pkgs
     python3 -m pip install jupyter tensorflow torch torchvision gym pandas scipy scipy-image --user
-    
+
     # install poetry
     sudo apt-get install python3-venv
     pip3 install --user poetry
